### ISSUE TITLE
Can apply / read color to a fragment of text in a TextBlock

### ISSUE THREAD

**Issue by z-jason** [jamalex/notion-py#203]

**Comment by jamalex** [comment]
When I first made notion-py, this wasn't possible to do even through Notion itself, but it now looks as if it is. 

Because we do automatic conversion to/from Markdown, which doesn't support specifying color, you can't directly set color to a part of the `title` (only to the whole block, using `myblock.color`). However, it looks as if you can manually set the property value directly using something like:
`myblock.set("properties.title", [['Only '], ['this part', [['h', 'red']]], [' is colored']])`

Not super clean -- but, possible! :)

**Comment by dcronin05** [comment]
Is there any way this method can be used to turn a specific chunk of text bold or italic as well? Markdown formatting seems to be getting ignored.
