### ISSUE TITLE
block sometimes needs an initial refresh to get most recent information

### ISSUE THREAD

**Issue by indirectlylit** [jamalex/notion-py#66]
Sometimes edits to blocks made in the Notion web UI are not immediately available through the API.

For example, create a sample script `test.py` like:

```python
client = NotionClient("[TOKEN]", monitor=False) 
page = client.get_block("[PAGE URL]")
print(page.title)
page.refresh()
print(page.title)
```

Create new page with title "A" and run the script on it. It will output

```
A
A
```

Edit the title to "B" in the web UI and re-run. It will output

```
A
B
```

I would expect it to output

```
B
B
```

**Comment by jamalex** [comment]
If you set `monitor=False`, it will not be monitoring for changes and auto-update. Try with `monitor=True`.

**Comment by indirectlylit** [comment]
In the example above, each run of `test.py` is independent. Monitoring should not be necessary, unless you're saying that there's a cache of some sort shared between multiple runs?

**Comment by jamalex** [comment]
There's a cache of some sort shared between multiple runs. :)

**Comment by jamalex** [comment]
But given monitoring can be turned off (and is currently broken), I think the cache should be re-thought a bit...

**Comment by indirectlylit** [comment]
the cache sounds useful, but I would expect it to be opt-in and off by default

**Comment by jamalex** [comment]
Sounds good. The main place it's essential is the combination of monitoring + callbacks + app restarts. Otherwise, if you add a bunch of listeners that do things, when you first start up the app you either miss all changes that happened while it was stopped, or you fire off a ton of unnecessary callbacks (which won't have accurate diffs in them). I'll think that through when I get monitoring going again.

**Comment by jamalex** [comment]
As of 0.0.25 (just released) it's now disabled by default, and can be enabled with NotionClient(..., enable_caching=True).
