### ISSUE TITLE
cv add_row not appending

### ISSUE THREAD

**Issue by andreas-globi** [jamalex/notion-py#70]
Using a table with some start value:
![](http://groovy.globi.ca/img/20191120-910f64053d1a6186589995f3f34e00be.png)

I add a row with
```
cv = client.get_collection_view(pageurl)
row = cv.collection.add_row()
row.name = "test 123"
```

![](http://groovy.globi.ca/img/20191120-0fca947c8f06be09c91f23613da47533.png)

This looks as expected.

Then I add another row
```
cv = client.get_collection_view(pageurl)
row = cv.collection.add_row()
row.name = "test 234"
```

But the row is not added to the bottom of the table

![](http://groovy.globi.ca/img/20191120-354680479673afdf96d9f4dfbd8fe5e4.png)

It's added after the manual entry but before the previous API entry.

**Comment by nabilridhwan** [comment]
Does sorting work?

**Comment by andreas-globi** [comment]
If there's a sort on the cv, it does show up correctly, but in the absence of a sort, it should be appending to the end.

**Comment by jamalex** [comment]
Addressed in https://github.com/jamalex/notion-py/pull/85, which will be released in an upcoming version. Note that it may not behave quite as expected for old collections that don't have fully fleshed out `page_sort` array set, but dragging some items around a bit in the UI should reset `page_sort` so that this will once again behave as expected. It loops over and updates all views on the main database, but probably won't do the same on linked databases, which have their own views.
