### ISSUE TITLE
zip() for parallel iteration when using get_property method is not reliable

### ISSUE THREAD

**Issue by jlmanaloto** [jamalex/notion-py#79]
I've observed that when using `zip()` for parallel iteration, the returned properties were incorrect. The code I used was:
```
researcher = row.get_property("Researcher")
infra = row.get_property("Infra")
for r, i in zip(researcher, infra):
    r_name = r.full_name
    i_name = i.full_name
```

However, without using parallel iteration, the expected property was returned.

```
researcher = row.get_property("Researcher")
infra = row.get_property("Inrfa")
for r in researcher:
    r_name = r.full_name
for i in infra:
    i_name = i.full_name
```

**Comment by jamalex** [comment]
Hmm, there are no generators or lazy evaluation in there, so zip wouldn't affect anything. I'm not sure what types of properties those are, but I'm guessing lists of People. My guess is that you sometimes have a different number of people in each of this lists, so zipping won't work as desired. As this is about the Python language rather than this library, I'm going to close the issue, but please reopen with more details of you disagree. Thanks!
